## To encourage contributors to use issue templates, we don't allow blank issues
blank_issues_enabled: false

contact_links:
  - name: 'Question'
    url: 'https://github.com/alphasine/AlphasineAssistant/discussions'
    about: 'Please ask and answer questions here'